languageCode = 'zh-cn'
title ="Waytrue's Braindump"
theme = "lugo"
disablePathToLower = true
[markup.goldmark.renderer]
hardWraps = true
unsafe = true
[markup.goldmark.extensions]
footnote = true
[permalinks]
medic = '/:filename/'
english = '/:filename/'

[params]
logoUrl = '/favicon.svg'

